# Generated by Django 5.1 on 2024-08-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User5',
        ),
    ]
