# Generated by Django 5.1 on 2024-08-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='accepted',
            new_name='is_accepted',
        ),
    ]
