# Generated by Django 5.1 on 2024-08-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_rename_accepted_interest_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
