# Generated by Django 5.1 on 2024-08-23 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_interest_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='interests_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
